name: Microsite

on:
 pull_request:
   branches: [docs]
  push:
    branches: [docs]

jobs:
  build:
    name: Generate Microsite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch (fast)
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Java and Scala
        uses: olafurpg/setup-scala@v5
        with:
          java-version: adopt@1.8

      - name: Install NodeJS 12
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Cache ivy2
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Cache coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-sbt-coursier-cache-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Cache sbt
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-cache-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

#      - name: Cache yarn
#        uses: actions/cache@v1
#        with:
#          path: '**/node_modules'
#          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}

      - name: Build
        run: ./build.sh

      - name: Publish
        if: github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build/cats-effect
          publish_branch: test-gh-pages
